image:
  repository: transcoder
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

transcoderConfig:
  additionalEnvs: []

transcoderRunAs:
  user: 1000
  group: 1000

transcoderStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  media:
    type: hostPath
    hostPathConfig:
      hostPath: "/mnt/media"
  additionalStorages: []