apiVersion: v1
kind: Service
metadata:
  name: {{ include "transcoder.fullname" . }}
  labels:
    {{- include "transcoder.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: placeholder
  selector:
    {{- include "transcoder.selectorLabels" . | nindent 4 }}